<div id="userRightDiv">
	<h1>Zoho to SEEK FEED <span>(Automatically pull jobs from zoho and upload to seek.)</span></h1>
	<div class="userContent">
	<h2>SEEK Fastlane</h2>
		<p class="importantnotice">
			Based on the credentials you provided in Seek Credential settings and Zoho Credentials, the system will automatically pull data from Zoho. An right XML will be generated by the system and push automatically to SEEK Fastlane.<br />
			<h3>
			Do you want to post the Jobs to SEEK ? 
			</h3>
		<ul class="seekconfirmaiton">		
			<li><a href="index.php?pg=seek">Post jobs to SEEK</a></li>
			<li><a href="index.php?pg=seekfeed">Cancel</a></li>
		</ul>
		</p>
	</div>
</div>